create table if not exists public.athletes (
    id bigint generated by default as identity primary key,
    name text not null,
    sex text not null check (sex in ('남', '여')),
    category text not null check (
        category in ('국가대표 후보', '청소년 대표', '꿈나무')
    ),
    created_at timestamptz not null default now()
);

alter table public.athletes enable row level security;

grant all on table public.athletes to service_role;
grant usage, select on sequence public.athletes_id_seq to service_role;
